import { useState } from 'react';
import { ChevronDown, ChevronUp, FileText, Calendar, Key } from 'lucide-react';

export default function ReportViewer({ report }) {
  const [expandedSections, setExpandedSections] = useState(
    report?.sections?.reduce((acc, _, index) => ({ ...acc, [index]: true }), {}) || {}
  );

  const toggleSection = (index) => {
    setExpandedSections((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  if (!report || !report.title) {
    return (
      <div className="flex items-center justify-center h-full text-[#64748b]">
        No report data available
      </div>
    );
  }

  const formatDate = (dateString) => {
    if (!dateString) return 'Unknown date';
    try {
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return dateString;
    }
  };

  return (
    <div className="w-full h-full overflow-y-auto bg-[#f8fafc] p-6">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="bg-white rounded-xl shadow-sm border border-[#e2e8f0] p-6 mb-6">
          <div className="flex items-start gap-3 mb-4">
            <div className="p-2 bg-[#3b82f6] rounded-lg">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-[#1e293b]">{report.title}</h1>
              <p className="text-sm text-[#64748b] mt-1">{report.summary}</p>
            </div>
          </div>
          
          {/* Meta info */}
          <div className="flex items-center gap-4 text-xs text-[#64748b] border-t border-[#e2e8f0] pt-4">
            <div className="flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5" />
              <span>Generated: {formatDate(report.generatedAt)}</span>
            </div>
            {report.sections && (
              <div className="flex items-center gap-1">
                <FileText className="w-3.5 h-3.5" />
                <span>{report.sections.length} sections</span>
              </div>
            )}
          </div>
        </div>

        {/* Key Points */}
        {report.keyPoints && report.keyPoints.length > 0 && (
          <div className="bg-gradient-to-r from-[#10b981] to-[#059669] rounded-xl shadow-sm p-6 mb-6 text-white">
            <div className="flex items-center gap-2 mb-4">
              <Key className="w-5 h-5" />
              <h2 className="text-lg font-semibold">Key Points</h2>
            </div>
            <ul className="space-y-2">
              {report.keyPoints.map((point, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="flex-shrink-0 w-5 h-5 rounded-full bg-white/20 flex items-center justify-center text-xs font-medium">
                    {index + 1}
                  </span>
                  <span className="text-sm text-white/90">{point}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Sections */}
        <div className="space-y-3">
          <h2 className="text-lg font-semibold text-[#1e293b] mb-4">Detailed Sections</h2>
          {report.sections && report.sections.map((section, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-sm border border-[#e2e8f0] overflow-hidden"
            >
              <button
                onClick={() => toggleSection(index)}
                className="w-full flex items-center justify-between p-4 hover:bg-[#f8fafc] transition-colors"
              >
                <h3 className="font-semibold text-[#1e293b]">{section.heading}</h3>
                {expandedSections[index] ? (
                  <ChevronUp className="w-5 h-5 text-[#64748b]" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-[#64748b]" />
                )}
              </button>
              
              {expandedSections[index] && (
                <div className="px-4 pb-4">
                  <div className="pt-2 border-t border-[#e2e8f0]">
                    <p className="text-sm text-[#475569] leading-relaxed whitespace-pre-wrap">
                      {section.content}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-6 text-center text-xs text-[#94a3b8]">
          <p>Report generated by AI Study Companion</p>
        </div>
      </div>
    </div>
  );
}
